/* eslint-disable object-curly-newline */
export const defaultValuesGraphHead = {
  boy: {
    dangerHigh: [
      { x: 0, y: 36.9 },
      { x: 2, y: 41.4 },
      { x: 4, y: 43.9 },
      { x: 5, y: 45.6 },
      { x: 8, y: 46.9 },
      { x: 10, y: 47.8 },
      { x: 12, y: 48.5 },
      { x: 14, y: 49.0 },
      { x: 16, y: 49.5 },
      { x: 18, y: 49.9 },
      { x: 20, y: 50.3 },
      { x: 22, y: 50.5 },
      { x: 24, y: 50.8 },
    ],
    warningHigh: [
      { x: 0, y: 35.9 },
      { x: 2, y: 40.4 },
      { x: 4, y: 42.9 },
      { x: 5, y: 44.6 },
      { x: 8, y: 45.8 },
      { x: 10, y: 46.8 },
      { x: 12, y: 47.4 },
      { x: 14, y: 47.9 },
      { x: 16, y: 48.4 },
      { x: 18, y: 48.8 },
      { x: 20, y: 49.1 },
      { x: 22, y: 49.4 },
      { x: 24, y: 49.7 },
    ],
    normal: [
      { x: 0, y: 34.5 },
      { x: 2, y: 39.2 },
      { x: 4, y: 41.6 },
      { x: 5, y: 43.4 },
      { x: 8, y: 44.5 },
      { x: 10, y: 45.4 },
      { x: 12, y: 46.1 },
      { x: 14, y: 46.6 },
      { x: 16, y: 47.0 },
      { x: 18, y: 47.4 },
      { x: 20, y: 47.7 },
      { x: 22, y: 48.0 },
      { x: 24, y: 48.3 },
    ],
    warningLow: [
      { x: 0, y: 33.3 },
      { x: 2, y: 37.9 },
      { x: 4, y: 40.4 },
      { x: 5, y: 42.1 },
      { x: 8, y: 43.3 },
      { x: 10, y: 44.1 },
      { x: 12, y: 44.8 },
      { x: 14, y: 45.3 },
      { x: 16, y: 45.7 },
      { x: 18, y: 46.0 },
      { x: 20, y: 46.4 },
      { x: 22, y: 46.7 },
      { x: 24, y: 46.9 },
    ],
    dangerLow: [
      { x: 0, y: 32.2 },
      { x: 2, y: 36.9 },
      { x: 4, y: 39.4 },
      { x: 5, y: 41.0 },
      { x: 8, y: 42.2 },
      { x: 10, y: 43.0 },
      { x: 12, y: 43.7 },
      { x: 14, y: 44.2 },
      { x: 16, y: 44.5 },
      { x: 18, y: 44.8 },
      { x: 20, y: 45.2 },
      { x: 22, y: 45.5 },
      { x: 24, y: 45.7 },
    ],
  },
  girl: {
    dangerHigh: [
      { x: 0, y: 36.1 },
      { x: 2, y: 40.5 },
      { x: 4, y: 43.0 },
      { x: 5, y: 44.7 },
      { x: 8, y: 45.9 },
      { x: 10, y: 46.8 },
      { x: 12, y: 47.4 },
      { x: 14, y: 48.0 },
      { x: 16, y: 48.5 },
      { x: 18, y: 48.8 },
      { x: 20, y: 49.2 },
      { x: 22, y: 49.5 },
      { x: 24, y: 49.8 },
    ],
    warningHigh: [
      { x: 0, y: 35.1 },
      { x: 2, y: 39.5 },
      { x: 4, y: 41.9 },
      { x: 5, y: 43.6 },
      { x: 8, y: 44.8 },
      { x: 10, y: 45.7 },
      { x: 12, y: 46.4 },
      { x: 14, y: 46.8 },
      { x: 16, y: 47.3 },
      { x: 18, y: 47.7 },
      { x: 20, y: 48.0 },
      { x: 22, y: 48.4 },
      { x: 24, y: 48.7 },
    ],
    normal: [
      { x: 0, y: 34.0 },
      { x: 2, y: 38.3 },
      { x: 4, y: 40.6 },
      { x: 5, y: 42.2 },
      { x: 8, y: 43.4 },
      { x: 10, y: 44.3 },
      { x: 12, y: 44.9 },
      { x: 14, y: 45.4 },
      { x: 16, y: 45.8 },
      { x: 18, y: 46.3 },
      { x: 20, y: 46.6 },
      { x: 22, y: 46.9 },
      { x: 24, y: 47.2 },
    ],
    warningLow: [
      { x: 0, y: 32.8 },
      { x: 2, y: 37.0 },
      { x: 4, y: 39.3 },
      { x: 5, y: 40.9 },
      { x: 8, y: 42.0 },
      { x: 10, y: 42.9 },
      { x: 12, y: 43.5 },
      { x: 14, y: 44.0 },
      { x: 16, y: 44.4 },
      { x: 18, y: 44.8 },
      { x: 20, y: 45.2 },
      { x: 22, y: 45.5 },
      { x: 24, y: 45.8 },
    ],
    dangerLow: [
      { x: 0, y: 31.8 },
      { x: 2, y: 36.0 },
      { x: 4, y: 38.2 },
      { x: 5, y: 39.8 },
      { x: 8, y: 40.9 },
      { x: 10, y: 41.7 },
      { x: 12, y: 42.4 },
      { x: 14, y: 42.9 },
      { x: 16, y: 43.3 },
      { x: 18, y: 43.7 },
      { x: 20, y: 44.0 },
      { x: 22, y: 44.3 },
      { x: 24, y: 44.6 },
    ],
  },
};

export const defaultValuesPlagiocephaly = {
  lineIndicator: [
    { x: 2.6, y: 24.8 },
    { x: 3, y: 23 },
    { x: 4, y: 19 },
    { x: 5, y: 15.5 },
    { x: 6, y: 12.9 },
    { x: 7, y: 10.4 },
    { x: 8, y: 8.8 },
    { x: 9, y: 7 },
    { x: 10, y: 5.8 },
    { x: 11, y: 4.8 },
    { x: 12, y: 3.8 },
    { x: 13, y: 2.9 },
    { x: 14, y: 2.3 },
    { x: 15, y: 1.9 },
    { x: 16, y: 1.5 },
    { x: 17, y: 1.2 },
    { x: 18, y: 1 },
  ],
  barIndicator: [
    { x: 0, y: 20 },
    { x: 1, y: 20 },
    { x: 2, y: 20 },
    { x: 3, y: 20 },
    { x: 4, y: 20 },
    { x: 5, y: 20 },
    { x: 6, y: 15 },
    { x: 7, y: 10 },
    { x: 8, y: 10 },
    { x: 9, y: 10 },
    { x: 10, y: 10 },
    { x: 11, y: 10 },
    { x: 12, y: 10 },
    { x: 13, y: 10 },
    { x: 14, y: 10 },
    { x: 15, y: 10 },
    { x: 16, y: 10 },
    { x: 17, y: 10 },
    { x: 18, y: 10 },
  ],
  lineHighIndicator: [
    { x: 0, y: 20 },
    { x: 1, y: 20 },
    { x: 2, y: 20 },
    { x: 3, y: 20 },
    { x: 4, y: 20 },
    { x: 5, y: 20 },
    { x: 6, y: 20 },
    { x: 7, y: 20 },
    { x: 8, y: 20 },
    { x: 9, y: 20 },
    { x: 10, y: 20 },
    { x: 11, y: 20 },
    { x: 12, y: 20 },
    { x: 13, y: 20 },
    { x: 14, y: 20 },
    { x: 15, y: 20 },
    { x: 16, y: 20 },
    { x: 17, y: 20 },
    { x: 18, y: 20 },
  ],
  lineModerateIndicator: [
    { x: 0, y: 10 },
    { x: 1, y: 10 },
    { x: 2, y: 10 },
    { x: 3, y: 10 },
    { x: 4, y: 10 },
    { x: 5, y: 10 },
    { x: 6, y: 10 },
    { x: 7, y: 10 },
    { x: 8, y: 10 },
    { x: 9, y: 10 },
    { x: 10, y: 10 },
    { x: 11, y: 10 },
    { x: 12, y: 10 },
    { x: 13, y: 10 },
    { x: 14, y: 10 },
    { x: 15, y: 10 },
    { x: 16, y: 10 },
    { x: 17, y: 10 },
    { x: 18, y: 10 },
  ],
  lineLowIndicator: [
    { x: 0, y: 3 },
    { x: 1, y: 3 },
    { x: 2, y: 3 },
    { x: 3, y: 3 },
    { x: 4, y: 3 },
    { x: 5, y: 3 },
    { x: 6, y: 3 },
    { x: 7, y: 3 },
    { x: 8, y: 3 },
    { x: 9, y: 3 },
    { x: 10, y: 3 },
    { x: 11, y: 3 },
    { x: 12, y: 3 },
    { x: 13, y: 3 },
    { x: 14, y: 3 },
    { x: 15, y: 3 },
    { x: 16, y: 3 },
    { x: 17, y: 3 },
    { x: 18, y: 3 },
  ],
};

export const defaultValuesBrachycephaly = {
  lineHighIndicator: [
    { x: 0, y: 110 },
    { x: 1, y: 103.5 },
    { x: 2, y: 98.5 },
    { x: 3, y: 94 },
    { x: 4, y: 91 },
    { x: 5, y: 89 },
    { x: 6, y: 87.5 },
    { x: 7, y: 85.5 },
    { x: 8, y: 84.5 },
    { x: 9, y: 84 },
    { x: 10, y: 83.5 },
    { x: 11, y: 83 },
    { x: 12, y: 82.5 },
    { x: 13, y: 82 },
    { x: 14, y: 81.5 },
    { x: 15, y: 81 },
    { x: 16, y: 80.5 },
    { x: 17, y: 80.4 },
    { x: 18, y: 80.1 },
  ],
  barIndicator: [
    { x: 0, y: 100 },
    { x: 1, y: 100 },
    { x: 2, y: 100 },
    { x: 3, y: 100 },
    { x: 4, y: 100 },
    { x: 5, y: 90 },
    { x: 6, y: 90 },
    { x: 7, y: 90 },
    { x: 8, y: 90 },
    { x: 9, y: 90 },
    { x: 10, y: 90 },
    { x: 11, y: 90 },
    { x: 12, y: 90 },
    { x: 13, y: 90 },
    { x: 14, y: 90 },
    { x: 15, y: 90 },
    { x: 16, y: 90 },
    { x: 17, y: 90 },
    { x: 18, y: 90 },
  ],
  // barModerateLow: [
  //   { x: 0, y: 68.3 },
  //   { x: 1, y: 68.3 },
  //   { x: 2, y: 68.3 },
  //   { x: 3, y: 68.3 },
  //   { x: 4, y: 68.3 },
  //   { x: 5, y: 68.3 },
  //   { x: 6, y: 68.3 },
  //   { x: 7, y: 68.3 },
  //   { x: 8, y: 68.3 },
  //   { x: 9, y: 68.3 },
  //   { x: 10, y: 68.3 },
  //   { x: 11, y: 68.3 },
  //   { x: 12, y: 68.3 },
  //   { x: 13, y: 68.3 },
  //   { x: 14, y: 68.3 },
  //   { x: 15, y: 68.3 },
  //   { x: 16, y: 68.3 },
  //   { x: 17, y: 68.3 },
  //   { x: 18, y: 68.3 },
  // ],
  barMildLow: [
    { x: 0, y: 70 },
    { x: 1, y: 70 },
    { x: 2, y: 70 },
    { x: 3, y: 70 },
    { x: 4, y: 70 },
    { x: 5, y: 70 },
    { x: 6, y: 70 },
    { x: 7, y: 70 },
    { x: 8, y: 70 },
    { x: 9, y: 70 },
    { x: 10, y: 70 },
    { x: 11, y: 70 },
    { x: 12, y: 70 },
    { x: 13, y: 70 },
    { x: 14, y: 70 },
    { x: 15, y: 70 },
    { x: 16, y: 70 },
    { x: 17, y: 70 },
    { x: 18, y: 70 },
  ],
  normal: [
    { x: 0, y: 80 },
    { x: 1, y: 80 },
    { x: 2, y: 80 },
    { x: 3, y: 80 },
    { x: 4, y: 80 },
    { x: 5, y: 80 },
    { x: 6, y: 80 },
    { x: 7, y: 80 },
    { x: 8, y: 80 },
    { x: 9, y: 80 },
    { x: 10, y: 80 },
    { x: 11, y: 80 },
    { x: 12, y: 80 },
    { x: 13, y: 80 },
    { x: 14, y: 80 },
    { x: 15, y: 80 },
    { x: 16, y: 80 },
    { x: 17, y: 80 },
    { x: 18, y: 80 },
  ],
  barMildHight: [
    { x: 0, y: 90 },
    { x: 1, y: 90 },
    { x: 2, y: 90 },
    { x: 3, y: 90 },
    { x: 4, y: 90 },
    { x: 5, y: 90 },
    { x: 6, y: 90 },
    { x: 7, y: 90 },
    { x: 8, y: 90 },
    { x: 9, y: 90 },
    { x: 10, y: 90 },
    { x: 11, y: 90 },
    { x: 12, y: 90 },
    { x: 13, y: 90 },
    { x: 14, y: 90 },
    { x: 15, y: 90 },
    { x: 16, y: 90 },
    { x: 17, y: 90 },
    { x: 18, y: 90 },
  ],
  barModerateHight: [
    { x: 0, y: 100 },
    { x: 1, y: 100 },
    { x: 2, y: 100 },
    { x: 3, y: 100 },
    { x: 4, y: 100 },
    { x: 5, y: 100 },
    { x: 6, y: 100 },
    { x: 7, y: 100 },
    { x: 8, y: 100 },
    { x: 9, y: 100 },
    { x: 10, y: 100 },
    { x: 11, y: 100 },
    { x: 12, y: 100 },
    { x: 13, y: 100 },
    { x: 14, y: 100 },
    { x: 15, y: 100 },
    { x: 16, y: 100 },
    { x: 17, y: 100 },
    { x: 18, y: 100 },
  ],
  barSevere: [
    { x: 0, y: 110 },
    { x: 1, y: 110 },
    { x: 2, y: 110 },
    { x: 3, y: 110 },
    { x: 4, y: 110 },
    { x: 5, y: 110 },
    { x: 6, y: 110 },
    { x: 7, y: 110 },
    { x: 8, y: 110 },
    { x: 9, y: 110 },
    { x: 10, y: 110 },
    { x: 11, y: 110 },
    { x: 12, y: 110 },
    { x: 13, y: 110 },
    { x: 14, y: 110 },
    { x: 15, y: 110 },
    { x: 16, y: 110 },
    { x: 17, y: 110 },
    { x: 18, y: 110 },
  ],
  lineLowIndicator: [
    { x: 1.4, y: 60 },
    { x: 3, y: 65.05 },
    { x: 4, y: 69 },
    { x: 5, y: 71 },
    { x: 6, y: 73.5 },
    { x: 7, y: 74.5 },
    { x: 8, y: 75 },
    { x: 9, y: 76 },
    { x: 10, y: 77.5 },
    { x: 11, y: 78 },
    { x: 12, y: 78.5 },
    { x: 13, y: 79 },
    { x: 14, y: 79.3 },
    { x: 15, y: 79.5 },
    { x: 16, y: 79.6 },
    { x: 17, y: 79.8 },
    { x: 18, y: 79.9 },
  ],
};

export const defaultValuesDevelopmentGraph = {
  dateScore: [
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 26,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 27,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 28,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 29,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 30,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 31,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 32,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 33,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 34,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 35,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 36,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 37,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 38,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 39,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 40,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 1,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 2,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 3,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 4,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 5,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 6,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 7,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 8,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 9,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 10,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 11,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 12,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 13,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 14,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 15,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 16,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 17,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 18,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 19,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 20,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 21,
    },
    {
      date: '',
      score: null,
      f: false,
      af: false,
      cs: false,
      ch: false,
      pr: false,
      h: false,
      n: false,
      sgNumber: 22,
    },
  ],
};
