// // estatus -> Indica el color: 0 = negro, 1 = verde, 2 = rojo
export const HammerSmithType = {
  id: '',
  patientId: '', // Cuando es del formulario de valoración
  neuroMonitoringId: '', // Cuando es del formulario de neuroseguimiento
  neuroMonitoringPatientId: '', // Cuando es del formulario de neuroseguimiento
  doctorIdCreated: '',
  timestamp: '',
  createdAt: '',
  updatedAt: '',
  resultado: 0,
  resultadoAsimetria: {
    izquierda: 0,
    derecha: 0,
  },
  resultadosParciales: {
    extremidadesSuperiores: 0,
    extremidadesInferiores: 0,
    cuelloTronco: 0,
    secuencia: 0,
  },
  cuestionario: {
    // Preguntas
    paresCraneales: {
      titulo: 'Evaluación de la función de los pares craneales', // Título lateral
      valorSecciones: 0,
      valorSeccionesId: 0,
      secciones: [
        {
          subtitulo: 'Apariencia facial',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            // Preguntas
            {
              indicador:
                'Sonríe y/o reacciona a los estímulos cerrando los ojos y haciendo muecas',
              // estatus: 1,
              valor: 4,
              indicadorId: 1,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador:
                'Cierra los ojos pero no con firmeza Pobre expresión facial',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador: 'Inexpresiva No reacciona a los estímulos',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: '',
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "1",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "1",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
        {
          subtitulo: 'Movimientos Oculares',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            {
              indicador: 'Movimientos oculares conjugados normales',
              // estatus: 0,
              valor: 4,
              indicadorId: 1,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador:
                'Desviación intermitente o movimiento anormales itermitentes',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador:
                'Desviación permanente o movimientos anormales continuos',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: '',
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
        {
          subtitulo: 'Respuesta Auditíva',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            {
              indicador: 'Responde al estímulo desde ambos lados',
              // estatus: 1,
              valor: 4,
              indicadorId: 1,
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3,
              indicadorId: 3,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador: 'Arco incompleto o asimétrico',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador: 'No sigue',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: '',
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
        {
          subtitulo: 'Respuesta Visual',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            {
              indicador: 'Sigue el objeto en un arco completo',
              // estatus: 1,
              valor: 4,
              indicadorId: 1,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3,
              indicadorId: 3,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador:
                'Sigue el objeto en un arco incompleto, o de forma asimétrica',
              // estatus: 1,
              valor: 2,
              indicadorId: 5,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador: 'No sigue el objeto',
              // estatus: 1,
              valor: 1,
              indicadorId: 7,
              iconId: '',
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
        {
          subtitulo: 'Succión / Deglución',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            {
              indicador: 'Buena succión y deglución',
              // estatus: 1,
              valor: 4,
              indicadorId: 1,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3,
              indicadorId: 3,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador: 'Pobre succión y/o deglución',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador: 'No reflejo de succión, imposible deglutir',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: '',
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
      ],
    },
    movimientos: {
      titulo: 'Evalución de los movimientos', // Título lateral
      valorSecciones: 0,
      valorSeccionesId: 0,
      secciones: [
        {
          subtitulo: 'Cantidad',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            // Preguntas
            {
              indicador: 'Normales',
              // estatus: 1,
              valor: 4,
              indicadorId: 1,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador: 'Excesivos o lentos (perezosos)',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador: 'Muy escasos o ausentes',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: '',
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
        {
          subtitulo: 'Calidad',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            {
              indicador: 'Fluidos, suaves y alternantes',
              // estatus: 0,
              valor: 4,
              indicadorId: 1,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador: 'Bruscos, Entrecortados, Leve temblor',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador:
                'Bruscos, rígidos y sincrónicos. Espasmos en extensión. Atetoides, Atáxicos, Temblores intensos, Espasmos miociónicos. Distónicos',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: '',
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
      ],
    },
    tono: {
      titulo: 'Evaluación del tono', // Título lateral
      valorSecciones: 0,
      valorSeccionesId: 0,
      secciones: [
        {
          subtitulo: 'Bufanda',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            // Preguntas
            {
              indicador: 'Rango',
              // estatus: 1,
              valor: 4,
              indicadorId: 1,
              iconId: 'signo-de-la-bufanda-1',
              DI: 2,
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: 'signo-de-la-bufanda-2',
              DI: 1,
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador: 'D I escasos o ausentes',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: 'signo-de-la-bufanda-3',
              DI: 2,
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
        {
          subtitulo: 'Elevación pasiva del hombro',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            {
              indicador: 'Resistencia superable',
              // estatus: 0,
              valor: 4,
              indicadorId: 1,
              iconId: 'elevacion-pasiva-del-hombro-1',
              DI: 1,
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: 'Dificultad para vencer la resistencia',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador: 'No existe resistencia',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: 'elevacion-pasiva-del-hombro-2',
              DI: 1,
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador: 'Resistencia no superable',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: 'elevacion-pasiva-del-hombro-3',
              DI: 1,
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
        {
          subtitulo: 'Pronación / Supinación',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            {
              indicador:
                'Pronación y supinación completas, no existe resistencia',
              // estatus: 0,
              valor: 4,
              indicadorId: 1,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador:
                'Pronación y supinación completas. Existe resistencia, pero se puede vencer',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador:
                'No pronación / supinación completa Excesiva resistencia',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: '',
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
        {
          subtitulo: 'Aductores',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            {
              indicador: 'Rango 150º - 80ª',
              // estatus: 0,
              valor: 4,
              indicadorId: 1,
              iconId: 'aductores-de-cadera-1',
              DI: 2,
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '150º - 160º',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: 'aductores-de-cadera-2',
              DI: 1,
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador: '< 170º',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: 'aductores-de-cadera-3',
              DI: 1,
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador: '< 80º',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: 'aductores-de-cadera-4',
              DI: 1,
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
        {
          subtitulo: 'Ángulo poplítero',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            {
              indicador: 'Rango 150º - 100º',
              // estatus: 0,
              valor: 4,
              indicadorId: 1,
              iconId: 'angulo-popitleo-1',
              DI: 2,
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '150º - 160º',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: 'angulo-popitleo-2',
              DI: 1,
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador: '-90º o > 170º',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: 'angulo-popitleo-3',
              DI: 2,
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador: '< 80º',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: 'angulo-popitleo-4',
              DI: 1,
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
        {
          subtitulo: 'Dorsiflexión de tobillo',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            {
              indicador: 'Rango 30º - 85º',
              // estatus: 0,
              valor: 4,
              indicadorId: 1,
              iconId: 'dorsiflexión-de-tobillo-1',
              DI: 2,
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '20º - 30º',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: 'dorsiflexión-de-tobillo-2',
              DI: 1,
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador: '<20º o 90º',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: 'dorsiflexión-de-tobillo-3',
              DI: 2,
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador: '>90º',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: 'dorsiflexión-de-tobillo-4',
              DI: 1,
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
        {
          subtitulo: 'Pull to sit',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            {
              indicador: '',
              // estatus: 0,
              valor: 4,
              indicadorId: 1,
              iconId: 'pull-to-sit-1',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: 'pull-to-sit-2',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: 'pull-to-sit-3',
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
        {
          subtitulo: 'Suspensión ventral',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            {
              indicador: '',
              // estatus: 0,
              valor: 4,
              indicadorId: 1,
              iconId: 'suspension-ventral-1',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: 'suspension-ventral-2',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: 'suspension-ventral-3',
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
      ],
    },
    postura: {
      titulo: 'Evaluación de la postura', // Título lateral
      valorSecciones: 0,
      valorSeccionesId: 0,
      secciones: [
        {
          subtitulo: 'Cabeza en sedentación',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            // Preguntas
            {
              indicador: 'Recta: en la línea media',
              // estatus: 1,
              valor: 4,
              indicadorId: 1,
              iconId: 'cabeza-en-sedestación-1',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador:
                'Ligeramente inclinada lateral o hacia atrás o delante',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: 'cabeza-en-sedestación-2',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador: 'Marcadamente inclinada lateral o atrás o adelante',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: 'cabeza-en-sedestación-3',
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
        {
          subtitulo: 'Tronco en sedentación',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            {
              indicador: 'Recto',
              // estatus: 0,
              valor: 4,
              indicadorId: 1,
              iconId: 'tronco-en-sedestación-1',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador: 'Ligeramente encorvado o inclinado hacia un lado',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: 'tronco-en-sedestación-2',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: 'tronco-en-sedestación-3',
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
        {
          subtitulo: 'Brazos en reposo',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            {
              indicador:
                'En posición neutra, centrados o ligeramente flexionados',
              // estatus: 0,
              valor: 4,
              indicadorId: 1,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador:
                'Rotación interna o externa leve-modelada postura distónica intermitente',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador:
                'Marcada rotación externa o interna postura distónica o hemipléjica mantenida',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: '',
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
        {
          subtitulo: 'Manos',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            {
              indicador: 'Manos abiertas',
              // estatus: 0,
              valor: 4,
              indicadorId: 1,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador:
                'Pulgar aducto y/o manos cerradas de forma itermitente',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador: 'Pulgar aducto y/o manos cerradas de forma mantenida',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: '',
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
        {
          subtitulo: 'Piernas',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            {
              indicador:
                'Puede estar sentado Espalda recta pienas extendidas o ligeramente flexionadas las piernas en posición neutra rectas o ligeram. flexionadas',
              // estatus: 0,
              valor: 4,
              indicadorId: 1,
              iconId: 'piernas-en-sedestación-1',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: 'Ligera rotación interna o rotación externa',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador:
                'Puede estar sentado mantiene la espalda recta pero las rodillas flexionadas 15-20º Rotación marcada, interna o externa, a la altura de las caderas',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: 'piernas-en-sedestación-2',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador:
                'No puede estar sentado con espalda y piernas rectas, solo si están marcadamente flexionadas Postura fija en flexión o en extensión o contracturas a nivel de caderas y rodillas',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: 'piernas-en-sedestación-3',
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
        {
          subtitulo: 'Pies',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            {
              indicador:
                'Pies rectos en posición neutra Dedos rectos entre flexión y extensión',
              // estatus: 0,
              valor: 4,
              indicadorId: 1,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador:
                'Ligera rotación interna o externa Tendencia a puntillas o dedos hiperextendidos o encogidos de forma intermitente',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador:
                'Marcada rotación interna o externa de tobillo Tendencia continua a puntillas o dedos hiperextendidos o engogidos (garra)',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: '',
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
      ],
    },
    reflejosReacciones: {
      titulo: 'Reflejos y reacciones postulares', // Título lateral
      valorSecciones: 0,
      valorSeccionesId: 0,
      secciones: [
        {
          subtitulo: 'Reflejos osteotendinosos',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            // Preguntas
            {
              indicador: 'Se obtienen con facilidad: biceps, rodilla y tobillo',
              // estatus: 1,
              valor: 4,
              indicadorId: 1,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: 'Ligeramente exaltados: biceps, rodilla y tobillo',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador: 'Exaltados: biceps, rodilla y tobillo',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador: 'Clonus o ausentes: biceps, rodilla y tobillo',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: '',
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
        {
          subtitulo: 'Protección del brazo',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            {
              indicador: 'Brazo y mano extendidos',
              // estatus: 0,
              valor: 4,
              indicadorId: 1,
              iconId: 'proteccion-del-brazo-1',
              DI: 1,
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador: 'Brazo semiflexionado',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: 'proteccion-del-brazo-2',
              DI: 1,
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador: 'Blazo completamente flexionado',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: 'proteccion-del-brazo-3',
              DI: 1,
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
        {
          subtitulo: 'Suspensión vertical',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            {
              indicador: 'Simétrico y alternante',
              // estatus: 0,
              valor: 4,
              indicadorId: 1,
              iconId: 'suspension-vertical-1',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador: 'Una pierna patalea más, o pataleo pobre',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: 'suspension-vertical-2',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador:
                'No patalea incluso si es estimulado, o adopta postura en tijera',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: 'suspension-vertical-3',
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
        {
          subtitulo: 'Suspensión lateral',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            {
              indicador: '',
              // estatus: 0,
              valor: 4,
              indicadorId: 1,
              iconId: 'suspencion-lateral-1',
              DI: 1,
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: 'suspencion-lateral-2',
              DI: 1,
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: 'suspencion-lateral-3',
              DI: 1,
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: 'suspencion-lateral-4',
              DI: 1,
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
        {
          subtitulo: 'Paracaídas',
          valorIndicador: 0,
          valorAsimetria: '',
          indicadores: [
            {
              indicador: '(después de los 6 meses)',
              // estatus: 0,
              valor: 4,
              indicadorId: 1,
              iconId: 'paracaidas-1',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 3.5,
              indicadorId: 2,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 3,
              indicadorId: 3,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 2.5,
              indicadorId: 4,
              iconId: '',
            },
            {
              indicador: '(después de los 6 meses)',
              // estatus: 2,
              valor: 2,
              indicadorId: 5,
              iconId: 'paracaidas-2',
            },
            {
              indicador: '',
              // estatus: 1,
              valor: 1.5,
              indicadorId: 6,
              iconId: '',
            },
            {
              indicador: '',
              // estatus: 2,
              valor: 1,
              indicadorId: 7,
              iconId: '',
            },
          ],
          asimetrias: [
            {
              asimetria: 'I',
              // estatus: "I",
              valor: 'I',
              asimetriaId: 1,
            },
            {
              asimetria: 'D',
              // estatus: "D",
              valor: 'D',
              asimetriaId: 2,
            },
          ],
        },
      ],
    },
  },
};
